application:
  actions: actions
  web: pages
  runtimeManifest:
    packages:
      actions:
        license: Apache-2.0
        actions:
          pages:
            function: runtime/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              final: true